"""empty message

Revision ID: 1ddcc299f874
Revises: 6fae17304c69
Create Date: 2016-02-06 11:38:39.171000

"""

# revision identifiers, used by Alembic.
revision = '1ddcc299f874'
down_revision = '6fae17304c69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_entry', 'userDorm')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_entry', sa.Column('userDorm', sa.VARCHAR(length=50), nullable=True))
    ### end Alembic commands ###
