"""empty message

Revision ID: 6fae17304c69
Revises: None
Create Date: 2016-02-06 11:28:10.904000

"""

# revision identifiers, used by Alembic.
revision = '6fae17304c69'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_entry', sa.Column('userDorm', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_entry', 'userDorm')
    ### end Alembic commands ###
